name: Cron Job

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes

jobs:
  run-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run cron script
        run: node cron.js